name: Pack and Publish

on:
  release:
    types: [ created ]

  workflow_dispatch:

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0

      - name: Restore packages
        run: dotnet restore "Configs/Configs.csproj"

      - name: Build project
        run: dotnet build -c Release "Configs/Configs.csproj"

      - name: Pack project
        run: dotnet pack --no-restore --no-build -c Release "Configs/Configs.csproj" -o "./out" 
        
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./out/*.nupkg

      - name: List files
        run: |
          cd out
          ls
  
  publish:
    needs: build
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0
        
      - uses: actions/download-artifact@v2
        with:
          name: package

      - name: Publish package
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  publish_gh:
    needs: build
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0

      - name: Add GitHub as source
        run: dotnet nuget add source --username Eliasyoussef47 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"
        
      - uses: actions/download-artifact@v2
        with:
          name: package
        
      - name: List files
        run: ls
        
      - name: Publish package
        run: dotnet nuget push *.nupkg --source "github"
        
