# This is a basic workflow to help you get started with Actions

name: Pack and Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: 'windows-latest'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0
        
      - name: Restore packages
        run: dotnet restore "Configs/Configs.csproj"

      - name: Build project
        run: dotnet build -c Release "Configs/Configs.csproj"

      - name: Pack project
        run: dotnet pack --no-restore --no-build -c Release "Configs/Configs.csproj" -o .

  # This workflow contains a single job called "build"
  publish:
    needs: build
    runs-on: 'windows-latest'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Publish package
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
